subs.shape = 
(449820, 3)
vals.shape = 
(449820, 1)
siz.shape = 
(3,)
siz = 
[5000  153  185]
Traceback (most recent call last):
  File "marbleTests_zj.py", line 29, in <module>
    X = sptensor.sptensor(subs, vals, siz)
  File "/home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/sptensor.py", line 121, in __init__
    newval[(int)(loc[i])] = func(vals[i], newval[(int)(loc[i])])
  File "/data/zhaojing/software/anaconda/lib/python2.7/site-packages/numpy/matrixlib/defmatrix.py", line 316, in __getitem__
    out = N.ndarray.__getitem__(self, index)
KeyboardInterrupt
subs.shape = 
(449820, 3)
vals.shape = 
(449820, 1)
siz.shape = 
(3,)
siz = 
[5000  153  185]
Iteration 0: 2205762.68893
Iteration 0: Xi = 0.499999961873, dll = 10908165.8985, time = 1.044039011
subs2.shape = 
(447506, 3)
vals2.shape = 
(447506, 1)
siz2.shape = 
(3,)
siz2 = 
[5000  153  185]
./rank_25.sh: line 1: 30496 Terminated              python marbleTests_zj_rank25.py
Traceback (most recent call last):
  File "marbleTests_zj_rank75.py", line 14, in <module>
    file = open("/data/zhaojing/marble/tensor/subs1.csv")
IOError: [Errno 2] No such file or directory: '/data/zhaojing/marble/tensor/subs1.csv'
./rank_100.sh: line 1: 28455 Terminated              python marbleTests_zj_rank100.py
subs.shape = 
(449820, 3)
vals.shape = 
(449820, 1)
siz.shape = 
(3,)
siz = 
[5000  153  185]
Iteration 0: 2206200.70566
Iteration 0: Xi = 0.499999961617, dll = 10820498.7031, time = 1.11801695824
subs2.shape = 
(447506, 3)
vals2.shape = 
(447506, 1)
siz2.shape = 
(3,)
siz2 = 
[5000  153  185]
